version: "3.7"
services: 
    front:
        image: front:0.1
        build: ./front 
        ports: 
           - 80:80
    back:
        image: back:0.1
        build: ./backendpjt
        ports:
           - 8080:8080
        depends_on:
           - db
    db:
       image: mysql:5.7.33
       restart: always
       ports: 
         - 3306:3306
       environment: 
           MYSQL_ROOT_PASSWORD : ssafyD203!
           MYSQL_DATABASE : webrtctest
           MYSQL_USER : root
           MYSQL_PASSWORD : ssafyD203!